services:
    app:
        build:
            args:
                user: "${DOCKER_USER}"
                uid: "${DOCKER_UID}"
                ugroup: "${DOCKER_GROUP}"
                gid: "${DOCKER_GID}"
            context: ./
            dockerfile: Dockerfile
        image: "contabot"
        container_name: "contabot"
        hostname: "contabot"
        restart: unless-stopped
        working_dir: /var/www/
        depends_on:
            - redis
            - db
        volumes:
            - ./:/var/www
            - ./mnt/exe/Imagenes:/var/www/storage/images
            - ./docker-compose/php/custom.ini:/usr/local/etc/php/conf.d/custom.ini
        networks:
            - "contabot-net"
        environment:
            CONTAINER_ROLE: "${CONTAINER_ROLE}"
            DOCKER_USER: "${DOCKER_USER}"

    scheduler:
        image: "contabot"
        container_name: "contabot-scheduler"
        hostname: "contabot-scheduler"
        depends_on:
            - app
        volumes:
            - .:/var/www
        networks:
            - "contabot-net"
        environment:
            CONTAINER_ROLE: scheduler
            DOCKER_USER: "${DOCKER_USER}"

    queue:
        image: "contabot"
        container_name: "contabot-queue"
        hostname: "contabot-queue"
        depends_on:
            - app
            - redis
        volumes:
            - ./:/var/www
        networks:
            - "contabot-net"
        environment:
            CONTAINER_ROLE: queue
            DOCKER_USER: "${DOCKER_USER}"

    db:
        image: postgres
        restart: always
        container_name: "contabot-pgdb"
        hostname: "contabot-pgdb"
        environment:
            POSTGRES_PASSWORD: "${DB_PASSWORD}"
            POSTGRES_USER: "${DB_USERNAME}"
            POSTGRES_DB: "${DB_DATABASE}"
            PGDATA: /var/lib/postgresql/data/pgdata
        volumes:
            - ./pgdata:/var/lib/postgresql/data/pgdata
        ports:
            - "${DOCKER_HOST_DB_PORT}:${DOCKER_CONTAINER_DB_PORT}"
        networks:
            - "contabot-net"

    nginx:
        image: nginx:alpine
        container_name: "contabot-nginx"
        hostname: "contabot-nginx"
        restart: unless-stopped
        depends_on:
            - app
        ports:
            - "${DOCKER_HOST_PORT}:${DOCKER_CONTAINER_PORT}"
        volumes:
            - ./:/var/www
            - ./docker-compose/nginx/nginx.conf:/etc/nginx/nginx.conf
            - ./docker-compose/nginx/conf.d:/etc/nginx/conf.d
        networks:
            - "contabot-net"

    redis:
        container_name: "contabot-redis"
        hostname: "contabot-redis"
        image: redis:alpine
        ports:
            - "${DOCKER_HOST_REDIS_PORT}:${DOCKER_CONTAINER_REDIS_PORT}"
        volumes:
            - redis:/data
        networks:
            - "contabot-net"
    reverb:
        image: "contabot"
        container_name: laravel_reverb
        working_dir: /var/www/
        volumes:
          - .:/var/www/
        command: php artisan reverb:start --host=0.0.0.0 --port=8080
        ports:
          - "8080:8080"
        depends_on:
          - redis
        networks:
          - "contabot-net"

volumes:
    redis:
        driver: "local"

networks:
    contabot-net:
        driver: bridge
